### ISSUE TITLE
Plugin does not work with Kibana 5.5

### ISSUE THREAD

**Issue by samueldm** [sbeyn/kibana-plugin-traffic-sg#6]
Hi there,

I migrated my Kibana to 5.5. 
Kibana does not work anymore with the plugin installed. Here is the error message:

_Error: Uncaught TypeError: __webpack_require__(...).register is not a function (https://theserver:5601/bundles/kibana.bundle.js?v=15382:320)
    at window.onerror (https://theserver:5601/bundles/commons.bundle.js?v=15382:90:22680)_

If I uninstall the plugin, Kibana 55 works fine again. I also tried the latest version of the plugin. No success.

Could you please help ?
Thanks a lot in advance. This plugin has been very useful so far!

**Comment by nikhilno1** [comment]
I am having the same problem and would really like to use this plugin. Thanks.

**Comment by nikhilno1** [comment]
Any comments? Thanks.

**Comment by bigtoerag** [comment]
I really want to demo this to a new 5.5.2 dashboard as it fits the look and feel I want.  Any plans to tweak for a 5.5.x install?

Error is:
`Error: TypeError: __webpack_require__(...).register is not a function (http://192.168.0.148:5601/bundles/kibana.bundle.js?v=15443:282)
[2501]/window.onerror@http://192.168.0.148:5601/bundles/commons.bundle.js?v=15443:90:20832`

**Comment by TRISAF** [comment]
I'm feeling same errors, any update?

**Comment by sasubillis** [comment]
same errors with 5.6.2 version. Any fix available?
`
Version: 5.6.2
Build: 15543


Error: Uncaught TypeError: __webpack_require__(...).register is not a function (https://kibana-dev.corp.uber.internal/bundles/kibana.bundle.js?v=15543:335)
    at window.onerror (https://kibana-dev.corp.uber.internal/bundles/commons.bundle.js?v=15543:90:23914)
'

**Comment by Nico-DF** [comment]
@sasubillis I've found a way to fix it. I'll make a fork and propose an update on this issue. Until it's accepted, you're free to look up its content and modify your files accordingly. Modifications are made in file traffic_sg.js and traffic_sg_controller.js
